// app/(base-layout)/department/page.tsx
'use client'

import { Heading } from '@/components/shared/heading'
import { Pagination } from '@/components/ui/pagination'
import { fetchJson } from '@/lib/fetch'
import { apiLocalRoute, webRoute } from '@/lib/route'
import { useSearchParams, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import type { DepartmentMetaData } from '#/model'
import {
  DepartmentWelcomeItem,
  DepartmentWelcomeSkeleton,
} from '@/features/welcome/department'
import { SearchInput } from '@/components/ui/search-input'

export default function DepartmentIndex() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const [page, setPage] = useState<number>(
    Number.parseInt(searchParams.get('page') || '1') || 1
  )
  const [search, setSearch] = useState<string>(searchParams.get('search') || '')

  const [isLoading, setIsLoading] = useState<boolean>(false)
  const [departments, setDepartments] = useState<DepartmentMetaData>()

  useEffect(() => {
    setIsLoading(true)

    const getDepartments = async () => {
      try {
        const response = await fetchJson<DepartmentMetaData>(
          apiLocalRoute('department.index', { page, search })
        )

        if (response.status !== 200) {
          throw new Error(
            "Une erreur est survenue lors de l'affichage des départements"
          )
        }

        setDepartments(response.data)
      } catch (error) {
        console.error('Erreur lors de la récupération des départements:', error)
      } finally {
        setIsLoading(false)
      }
    }

    getDepartments()
  }, [page, search])

  const handlePageChange = (newPage: number) => {
    setPage(newPage)
    const params = { page: newPage }

    if (search && search.length > 0) {
      router.push(webRoute('department.index', { ...params, search }))
    } else {
      router.push(webRoute('department.index', params))
    }
  }

  const onSearchChange = (newSearch: string) => {
    setSearch(newSearch)
    router.push(webRoute('department.index', { search: newSearch, page }))
  }

  const onReset = () => {
    setSearch('')
    setPage(1)
    router.push(webRoute('department.index'))
  }
  return (
    <div className="container py-12">
      <Heading title="Nos départements" />

      {departments &&
        departments.meta.links &&
        departments.meta.links.length > 2 && (
          <div className="mb-5 flex justify-between items-start">
            <SearchInput
              onSearch={onSearchChange}
              onReset={onReset}
              lengthData={departments.meta.total}
              placeholder="Rechercher un départment"
            />
          </div>
        )}

      {isLoading ? (
        <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 mt-8">
          <DepartmentWelcomeSkeleton />
        </div>
      ) : (
        <>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 mt-8">
            {departments?.data.map((department) => (
              <DepartmentWelcomeItem dept={department} key={department.id} />
            ))}
          </div>

          {departments && (
            <div className="mt-8">
              <Pagination onPage={handlePageChange} meta={departments.meta} />
            </div>
          )}
        </>
      )}
    </div>
  )
}

// pages/department/index.vue
<script setup lang="ts">
import DepartmentCard from "@/components/features/department/DepartmentCard.vue";
import { getCollectionDepartments } from "@/services/other";
import type { DepartmentModel } from "@/types/model";
import { toast } from "vue-sonner";
import type { PaginatedResponse } from "../../types/paginate";

useHead({
  title: "Nos départements - Polytechnic Application",
});
definePageMeta({
  layout: "default",
});

type DepartmentPaginateProps = PaginatedResponse<DepartmentModel[]>;

const isPending = ref<boolean>(true);
const departments = ref<DepartmentPaginateProps>();
const router = useRouter();
const route = useRoute();

const numberPage = ref<number>(
  route.query.page ? parseInt(route.query.page as string) : 1
);

const fetchDepartments = async () => {
  try {
    isPending.value = true;

    const response = await getCollectionDepartments(numberPage.value);
    const data = await response.json();

    if (response.ok) {
      departments.value = data as DepartmentPaginateProps;
    } else {
      toast.error("Erreur", {
        description:
          (data as { message: string }).message || "Une erreur est survenue",
      });
    }
  } catch (error) {
    toast.error("Erreur", {
      description: `Impossible de récupèrer les départments`,
    });
  } finally {
    isPending.value = false;
  }
};

const onPage = async (page: number) => {
  numberPage.value = page;
  await router.push(`/department?page=${page}`);
  await fetchDepartments();
};

watch(
  () => route.query.page,
  (newPage) => {
    const pageNumber = newPage ? parseInt(newPage as string) : 1;
    if (pageNumber !== numberPage.value) {
      numberPage.value = pageNumber;
      fetchDepartments();
    }
  }
);

onMounted(() => {
  fetchDepartments();
});
</script>

<template>
  <div class="container my-12" v-if="isPending">
    <div class="section-page-header">
      <h2 class="section-page-title">Nos Départements</h2>
    </div>

    <LoaderContainer :is-card="true" />
  </div>

  <div
    class="container my-12"
    v-if="
      (!departments || (departments && departments.data.length === 0)) &&
      !isPending
    "
  >
    <div class="section-page-header">
      <h2 class="section-page-title">Nos Départements</h2>
    </div>
    <p>Pas de départements</p>
  </div>

  <div class="container my-12" v-if="departments">
    <div class="section-page-header">
      <h2 class="section-page-title">Nos Départements</h2>
    </div>

    <div
      class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 justify-center"
    >
      <DepartmentCard
        v-for="department in departments.data"
        :department="department"
        :key="department.id"
      />
    </div>

    <!-- Pagination -->
    <Pagination :onPage="onPage" :meta="departments" />
  </div>
</template>
