// pages/year-academic/index.vue
<script setup lang="ts">
import { ref, watch, onMounted } from "vue";
import { useRoute, useRouter } from "vue-router";
import { toast } from "vue-sonner";

import YearCard from "@/components/features/year/YearCard.vue";
import { getCollectionYears } from "@/services/other";
import type { YearModel } from "@/types/model";
import type { PaginatedResponse } from "@/types/paginate";

useHead({
  title: "Années académiques - Polytechnic Application",
});

definePageMeta({
  layout: "default",
});

type YearPaginateProps = PaginatedResponse<YearModel[]>;

const isPending = ref(true);
const years = ref<YearPaginateProps>();
const router = useRouter();
const route = useRoute();

const numberPage = ref(
  route.query.page ? parseInt(route.query.page as string) : 1
);

const fetchYears = async () => {
  try {
    isPending.value = true;

    const response = await getCollectionYears(numberPage.value);
    const data = await response.json();

    if (response.ok) {
      years.value = data as YearPaginateProps;
    } else {
      toast.error("Erreur", {
        description:
          (data as { message?: string }).message || "Une erreur est survenue lors du chargement.",
      });
    }
  } catch (error) {
    toast.error("Erreur", {
      description: "Impossible de récupérer les années académiques.",
    });
  } finally {
    isPending.value = false;
  }
};

const onPage = async (page: number) => {
  numberPage.value = page;
  await router.push(`/year-academic?page=${page}`);
  await fetchYears();
};

watch(
  () => route.query.page,
  (newPage) => {
    const pageNumber = newPage ? parseInt(newPage as string) : 1;
    if (pageNumber !== numberPage.value) {
      numberPage.value = pageNumber;
      fetchYears();
    }
  }
);

onMounted(fetchYears);
</script>
<template>
  <div class="container my-12 space-y-8">
    <div class="section-page-header">
      <h2 class="section-page-title text-2xl md:text-3xl font-semibold text-primary">
        Années académiques
      </h2>
      <p class="text-muted-foreground mt-1">
        Liste des années académiques disponibles à la Faculté Polytechnique.
      </p>
    </div>

    <!-- Chargement -->
    <LoaderContainer v-if="isPending" :is-card="true" />

    <!-- Aucun résultat -->
    <div v-else-if="!years || years.data.length === 0" class="text-center text-muted-foreground py-10">
      Aucune année académique disponible pour le moment.
    </div>

    <!-- Résultat -->
    <div v-else>
      <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6">
        <YearCard v-for="year in years.data" :key="year.id" :year="year" />
      </div>

      <!-- Pagination -->
      <Pagination :onPage="onPage" :meta="years" class="mt-8" />
    </div>
  </div>
</template>

// app/(base-layout)/year-academic/page.tsx
'use client'

import { Heading } from '@/components/shared/heading'
import { Pagination } from '@/components/ui/pagination'
import { fetchJson } from '@/lib/fetch'
import { apiRoute, webRoute } from '@/lib/route'
import { useSearchParams, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { SearchInput } from '@/components/ui/search-input'
import { BookOpen } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { YearMetaData } from '#/model'
import { YearCollection } from './year-collection'
import { Loader } from '@/components/ui/loader'

export default function YearIndex() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const [page, setPage] = useState<number>(
    Number.parseInt(searchParams.get('page') || '1') || 1
  )
  const [search, setSearch] = useState<string>(searchParams.get('search') || '')

  const [isLoading, setIsLoading] = useState<boolean>(false)
  const [years, setYears] = useState<YearMetaData>()

  useEffect(() => {
    setIsLoading(true)

    const getYears = async () => {
      try {
        const response = await fetchJson<YearMetaData>(
          apiRoute('year.index', { page, search })
        )

        if (response.status !== 200) {
          throw new Error(
            "Une erreur est survenue lors de l'affichage d'année académique"
          )
        }

        setYears(response.data)
      } catch (error) {
        console.error(
          "Erreur lors de la récupération d'année académique:",
          error
        )
      } finally {
        setIsLoading(false)
      }
    }

    getYears()
  }, [page, search])

  const handlePageChange = (newPage: number) => {
    setPage(newPage)
    const params = { page: newPage }

    if (search && search.length > 0) {
      router.push(webRoute('year.index', { ...params, search }))
    } else {
      router.push(webRoute('year.index', params))
    }
  }

  const onSearchChange = (newSearch: string) => {
    setSearch(newSearch)
    router.push(webRoute('year.index', { search: newSearch, page }))
  }

  const onReset = () => {
    setSearch('')
    setPage(1)
    router.push(webRoute('year.index'))
  }

  return (
    <div className="container py-12">
      <Heading title="Année Acadéique" />

      {years && years.meta.links && years.meta.links.length > 2 && (
        <div className="mb-5 flex justify-between items-start">
          <SearchInput
            onSearch={onSearchChange}
            onReset={onReset}
            lengthData={years.meta.total}
            placeholder="Rechercher une année académique"
          />
        </div>
      )}

      {isLoading ? (
        <Loader />
      ) : (
        <>
          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3 mt-8">
            {years?.data.map((year) => (
              <YearCollection key={year.id} year={year} />
            ))}
          </div>

          {years && years.data.length === 0 && (
            <div className="text-center py-12 border rounded-lg mt-8">
              <BookOpen className="mx-auto h-12 w-12 text-muted-foreground mb-4" />
              <h3 className="text-lg font-medium">Aucune option trouvée</h3>
              <p className="text-muted-foreground mt-2">
                Essayez de modifier vos critères de recherche ou consultez
                toutes nos options.
              </p>
              <Button onClick={onReset} className="mt-4">
                Voir toutes les options
              </Button>
            </div>
          )}

          {years && years.meta.last_page > 1 && (
            <div className="mt-8">
              <Pagination onPage={handlePageChange} meta={years.meta} />
            </div>
          )}
        </>
      )}
    </div>
  )
}
