// app/dashboard/department/page.tsx
'use client'

import { DepartmentMetaData } from '#/model'
import { TextLink } from '@/components/shared/text-link'
import { BreadcrumbsHeader } from '@/components/sidebar/breadcrumb-header'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Pagination } from '@/components/ui/pagination'
import { SearchInput } from '@/components/ui/search-input'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
  TableSkeleton,
} from '@/components/ui/table'
import { AdminLayout } from '@/layouts/admin-layout'
import { ago } from '@/lib/date-time'
import { apiLocalRoute, webRoute } from '@/lib/route'
import { excerpt } from '@/lib/utils'
import { Eye, Pen } from 'lucide-react'
import Link from 'next/link'
import { useRouter, useSearchParams } from 'next/navigation'
import { useEffect, useState } from 'react'

const items = [
  {
    title: 'Tableau de bord',
    href: webRoute('dashboard'),
  },
  {
    title: 'Départements',
    href: '#',
  },
]

export default function Page() {
  const searchParams = useSearchParams()
  const router = useRouter()
  const [page, setPage] = useState<number>(
    Number.parseInt(searchParams.get('page') || '1') || 1
  )
  const [search, setSearch] = useState<string>(searchParams.get('search') || '')

  const [isLoading, setIsLoading] = useState<boolean>(false)
  const [departments, setDepartments] = useState<DepartmentMetaData>()

  useEffect(() => {
    setIsLoading(true)

    const getDepartments = async () => {
      try {
        const response = await fetch(
          apiLocalRoute('~department.index', { page, search })
        )

        if (response.status !== 200) {
          throw new Error(
            "Une erreur est survenue lors de l'affichage des départements"
          )
        }

        const data = (await response.json()) as DepartmentMetaData

        setDepartments(data)
      } catch (error) {
        console.error('Erreur lors de la récupération des départements:', error)
      } finally {
        setIsLoading(false)
      }
    }

    getDepartments()
  }, [page, search])

  const handlePageChange = (newPage: number) => {
    setPage(newPage)
    const params = { page: newPage }

    if (search && search.length > 0) {
      router.push(webRoute('~department.index', { ...params, search }))
    } else {
      router.push(webRoute('~department.index', params))
    }
  }

  const onSearchChange = (newSearch: string) => {
    setSearch(newSearch)
    router.push(webRoute('~department.index', { search: newSearch, page }))
  }

  const onReset = () => {
    setSearch('')
    setPage(1)
    router.push(webRoute('~department.index'))
  }

  return (
    <>
      <BreadcrumbsHeader items={items} />
      <AdminLayout>
        {departments &&
          departments.meta.links &&
          departments.meta.links.length > 2 && (
            <div className="mb-5 flex justify-between items-start">
              <SearchInput
                onSearch={onSearchChange}
                onReset={onReset}
                lengthData={departments.meta.total}
                placeholder="Rechercher un départment"
              />
            </div>
          )}

        {isLoading ? (
          <div className="w-full mt-8">
            <TableSkeleton className="w-full" />
          </div>
        ) : (
          <>
            {departments && (
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Nom</TableHead>
                    <TableHead>Options</TableHead>
                    <TableHead>Créer</TableHead>
                    <TableHead className="lg:text-end">Actions</TableHead>
                  </TableRow>
                </TableHeader>

                <TableBody>
                  {departments.data.map((department) => {
                    return (
                      <TableRow key={department.id}>
                        <TableCell>
                          <TextLink
                            href={webRoute('~department.show', {
                              id: department.id,
                            })}
                          >
                            {excerpt(department.name, 40)}
                          </TextLink>
                        </TableCell>

                        <TableCell>
                          <Badge variant="secondary">
                            {department.options.length}
                          </Badge>
                        </TableCell>

                        <TableCell>
                          <p className="text-xs text-muted-foreground">
                            {ago(department.created_at)}
                          </p>
                        </TableCell>

                        <TableCell>
                          <div className="flex items-center gap-3 justify-end">
                            <Button variant="secondary" size="sm" asChild>
                              <Link
                                href={webRoute('~department.edit', {
                                  id: department.id,
                                })}
                              >
                                <Pen />
                              </Link>
                            </Button>

                            <Button variant="outline" size="sm" asChild>
                              <Link
                                href={webRoute('~department.show', {
                                  id: department.id,
                                })}
                              >
                                <Eye />
                              </Link>
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    )
                  })}
                </TableBody>
              </Table>
            )}

            {departments && (
              <div className="mt-8">
                <Pagination onPage={handlePageChange} meta={departments.meta} />
              </div>
            )}
          </>
        )}
      </AdminLayout>
    </>
  )
}

// pages/admin/department/index.vue
<script setup lang="ts">
import LoaderContainer from "@/components/LoaderContainer.vue";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import Pagination from "@/components/ui/pagination/Pagination.vue";
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table";
import { useAuth } from "@/composables/useAuth";
import { ago } from "@/lib/date-time";
import { excerpt } from "@/lib/utils";
import type { DepartmentModel } from "@/types/model";
import type { PaginatedResponse } from "@/types/paginate";
import { Eye, Pen } from "lucide-vue-next";
import { toast } from "vue-sonner";
import { getCollectionDepartments } from "../../../services/department";

useHead({
  title: "Gestion des cours - Polytechnic Application",
});

definePageMeta({
  layout: "admin",
  middleware: ["admin"],
});

type ModelCollectionProps = PaginatedResponse<DepartmentModel[]>;

const auth = useAuth();
const router = useRouter();
const route = useRoute();

const numberPage = ref<number>(
  route.query.page ? parseInt(route.query.page as string) : 1
);

const departments = ref<ModelCollectionProps | null>(null);
const isLoading = ref<boolean>(true);

const fetchDepartments = async () => {
  try {
    isLoading.value = true;

    if (!auth.session.value?.accessToken) {
      throw new Error("utilisateur non authentifié");
    }

    const response = await getCollectionDepartments(
      auth.session.value.accessToken,
      numberPage.value
    );
    const data = await response.json();

    if (response.ok) {
      departments.value = data as ModelCollectionProps;
    } else if (response.status == 401) {
      toast.warning("Session", {
        description: "Votre session a expiré, merci de vous reconnecter",
      });
      auth.logout();
    } else {
      toast.error("Erreur", {
        description:
          (data as { message: string }).message || "Une erreur est survenue",
      });
    }
  } catch (error) {
    toast.error("Erreur", {
      description: "Impossible de charger les cours",
    });
  } finally {
    isLoading.value = false;
  }
};

const onPage = async (page: number) => {
  numberPage.value = page;
  await router.push(`/admin/department?page=${page}`);
  await fetchDepartments();
};

watch(
  () => route.query.page,
  (newPage) => {
    const pageNumber = newPage ? parseInt(newPage as string) : 1;
    if (pageNumber !== numberPage.value) {
      numberPage.value = pageNumber;
      fetchDepartments();
    }
  }
);

onMounted(async () => {
  await fetchDepartments();
});
</script>

<template>
  <Card>
    <CardHeader>
      <div class="flex items-center gap-4 justify-between">
        <div>
          <CardTitle>Gestion des départements</CardTitle>
          <CardDescription>
            Gérez les départments de la faculté de polytechinique
          </CardDescription>
        </div>
      </div>
    </CardHeader>
    <CardContent>
      <!-- Loader -->
      <LoaderContainer v-if="isLoading" />

      <!-- Aucun cours -->
      <div v-else-if="!departments?.data?.length" class="text-center py-8">
        <p class="text-muted-foreground">Aucun département trouvé</p>
      </div>

      <!-- Table des cours -->
      <div v-else class="space-y-4">
        <Table>
          <TableHeader>
            <TableRow>
              <TableHead>Nom</TableHead>
              <TableHead>Alias</TableHead>
              <TableHead>Options</TableHead>
              <TableHead>Création</TableHead>
              <TableHead class="text-right">Actions</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            <TableRow
              v-for="department in departments.data"
              :key="department.id"
            >
              <TableCell class="font-medium">
                {{ excerpt(department.name, 30) }}
              </TableCell>

              <TableCell class="font-medium">
                {{ excerpt(department.alias, 20) }}
              </TableCell>

              <TableCell class="font-medium">
                <Badge variant="outline">
                  {{ department.options.length }}
                </Badge>
              </TableCell>

              <TableCell>
                <p class="text-sm text-muted-foreground">
                  {{ ago(department.created_at) }}
                </p>
              </TableCell>

              <TableCell>
                <div class="flex items-center gap-4 lg:justify-end">
                  <Button size="sm" variant="outline" :as-child="true">
                    <NuxtLink :href="`/admin/department/${department.id}/edit`">
                      <Pen :size="15" />
                    </NuxtLink>
                  </Button>
                  <Button size="sm" variant="secondary" :as-child="true">
                    <NuxtLink :href="`/admin/department/${department.id}`">
                      <Eye :size="15" />
                    </NuxtLink>
                  </Button>
                </div>
              </TableCell>
            </TableRow>
          </TableBody>
        </Table>

        <!-- Pagination -->
        <Pagination v-if="departments" :onPage="onPage" :meta="departments" />
      </div>
    </CardContent>
  </Card>
</template>
