// app/(auth)/reset-password/[token]/page.tsx
'use client'

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { ResetPasswordForm } from './reset-form'
import { useParams, useRouter, useSearchParams } from 'next/navigation'
import { useState } from 'react'
import { ResetPasswordSchemaInfer } from '@/definitions/auth'
import { toast } from 'sonner'
import { webRoute } from '@/lib/route'
import { resetPasswordUser } from '@/repositories/auth'

const ResetPassword = () => {
  const [processing, setProcessing] = useState<boolean>(false)

  const router = useRouter()

  const params = useParams<{ token: string }>()
  const searchParams = useSearchParams()
  const email = searchParams.get('email')

  const onSubmit = async (values: ResetPasswordSchemaInfer) => {
    setProcessing(true)

    try {
      const json = await resetPasswordUser({
        ...values,
        token: params.token,
      })

      toast.info('Action', {
        description: json.data.email,
      })

      router.push(webRoute('login'))
    } catch (error) {
      toast.error('Une erreur est survenue', {
        description:
          (error as { message?: string })?.message || 'Erreur inconnue',
      })
    } finally {
      setProcessing(false)
    }
  }

  return (
    <div>
      <Card className="rounded-xl">
        <CardHeader className="px-10 pt-8 pb-0 text-center">
          <CardTitle className="text-xl">
            Réinitialisation du mot de passe
          </CardTitle>
          <CardDescription>
            Veuillez entrer votre nouveau mot de passe ci-dessous
          </CardDescription>
        </CardHeader>
        <CardContent className="px-10 py-8">
          <ResetPasswordForm
            email={email ?? ''}
            processing={processing}
            onSubmit={onSubmit}
          />
        </CardContent>
      </Card>
    </div>
  )
}

export default ResetPassword

// pages/auth/reset-password/[token].vue
<script setup lang="ts">
import ResetPasswordForm from "@/components/features/auth/ResetPasswordForm.vue";
import { resetPasswordUser } from "@/services/auth";
import type { ResetPasswordModel } from "@/types/model";
import type { ValidatorErrorProps } from "@/types/util";
import { ref } from "vue";
import { useRoute } from "vue-router";
import { toast } from "vue-sonner";
import type { ResetPasswordSchemaInfer } from "~/definitions/auth";

useHead({
  title: "Réinitialisation de mot de passe - Polytechnic Application",
});

definePageMeta({
  layout: "auth",
});

const route = useRoute();
const router = useRouter();

const token = route.params.token as string;
const email = route.query.email as string;

const validator = ref<ValidatorErrorProps | null>(null);
const redirecting = ref(false);

const onSubmit = async (values: ResetPasswordSchemaInfer) => {
  validator.value = null;

  const response = await resetPasswordUser({ ...values, token });

  const data = await response.json();

  if (response.ok) {
    redirecting.value = true;
    const state = data as ResetPasswordModel;

    toast("Message", {
      description: state.message,
    });

    if (state.is_update) {
      router.replace("/auth/login");
    }

    return true;
  } else if (response.status === 422) {
    validator.value = data as ValidatorErrorProps;
  } else {
    toast("Problème", {
      description: (data as { message: string }).message,
    });
  }

  return false;
};
</script>

<template>
  <Card>
    <CardHeader class="text-center">
      <CardTitle>Réinitialisation du mot de passe</CardTitle>
      <CardDescription>
        Veuillez entrer votre nouveau mot de passe ci-dessous
      </CardDescription>
    </CardHeader>
    <CardContent>
      <ResetPasswordForm :onSubmit="onSubmit" :email="email" />
    </CardContent>
  </Card>
</template>
